#!/bin/bash
ip=`echo $SSH_CONNECTION | cut -d " " -f 1`

logger -t ssh-wrapper $USER login from $ip

echo "User $USER just logged in from $ip" | sendemail -q -u "SSH Login tyche-c" -f "NR151 <NR151@siterovi.cz>" -t "sitera@civ.zcu.cz" -s smtp.zcu.cz &
